name: Publish assets

on:
  workflow_run:
    workflows: [CI]
    types: [completed]
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - run: nix -L build .#parser-src
      - name: Upload parser sources
        uses: actions/upload-artifact@v4
        with:
          name: tree-sitter-haskell-src
          path: result/src

      - run: nix -L build .#parser-wasm
      - name: Upload wasm binary
        uses: actions/upload-artifact@v4
        with:
          name: tree-sitter-haskell-wasm
          path: result/tree-sitter-haskell.wasm
