name: CI

on:
  push:
    branches:
      - "**"
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  test:
    name: test / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macOS-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - uses: mymindstorm/setup-emsdk@v11
        with:
          version: 3.0.1
          actions-cache-folder: 'emsdk-cache'
      - if: runner.os == 'Linux'
        run: echo "CXX=g++-9" >> $GITHUB_ENV
      - run: npm install
      - run: npm test
      - run: npm run examples
      - run: npm run examples-wasm
