name: CI

on:
  push:
    branches:
      - "**"
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  test:
    name: tree-sitter-haskell / ${{ matrix.runs-on }}

    strategy:
      fail-fast: false
      runs-on: [ubuntu-latest, macOS-latest]
      include:
      - runs-on: ubuntu-latest
        cxx: [g++-9]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - if: matrix.cxx
        run: echo "CXX=${{ matrix.cxx }}" >> $GITHUB_ENV
      - run: npm install
      - run: npm test
      - run: npm run examples
