name: CI

on:
  push:
    branches:
      - "**"
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  test:
    name: test / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macOS-latest, ubuntu-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install emscripten
        uses: mymindstorm/setup-emsdk@v10
        with:
          version: '2.0.24'

      - name: Set C/C++ compiler
        if: runner.os == 'Linux'
        run: |
          echo "CC=gcc-9" >> $GITHUB_ENV
          echo "CXX=g++-9" >> $GITHUB_ENV

      - name: Build tree-sitter-haskell
        run: npm install

      - name: Run tests
        run: npm test

      - name: Parse examples
        run: npm run examples

      - name: Parse examples with web binding
        run: |
          make -B node_modules/web-tree-sitter
          ./script/parse-examples wasm
